config/routes.rb
Rails.application.routes.draw do
  # HTTP is a protocol where we use HTTP verbs to interact with URI's (URL's)

  # GET "action view" => "controller name # controller action"
  get 'index' => 'demos#index'
  get 'welcome' => 'demos#welcome'

  # POST
  # PUT
  # PATCH
  # DELETE




 
  root 'tasks#index'

  get 'tasks/:id' => 'tasks#show', constraints: {id: /\d+/}, as: 'task'

  
end

app/models/task.rb
class Task < ActiveRecord::Base
	# We automaticly get a primary key called id
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
	layout 'demo_application'

	def index	
		
	# By default, rails will attempt to load the associated "index"	view:
	# app/views/demo/index.html.erb
	end

	def welcome		
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index	
		@tasks = Task.order(:description)

		if rand(0..1).zero?
			@chore = "Sweeping"
		else
			@chore = "Vacuuming"
		end	
	end

	def show
		@task = Task.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/demos/index.html.erb
<li><%= link_to('Welcome Page', welcome_path) %></li><br>

<h1>Demo View</h1><br>

app/views/demos/welcome.html.erb
<li><%= link_to('Back', index_path) %></li><br>

<h1>Welcome View</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To do List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<header><h1>To-Do List</h1></header>

<%= yield %>

</body>
</html>

app/views/layouts/demo_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<ul>
	<% @tasks.each do |task| %>
		<li><%= link_to(task.description, task) %></li>
	<% end %>
</ul>

<% 5.times do %>
	<h2><%= @chore %></h2>
<% end %>

app/views/tasks/show.html.erb
<p><%= @task.description %></p>